### ISSUE TITLE
你好，打扰下问个关于词典的问题

### ISSUE THREAD

**Issue by xp12047** [Frefreak/rime-zrm-wubi#1]
我看了你改的那个zrm2000词典。我觉得好像不大对？那个阿布不应该是aabud或者aabudm嘛？对于86五笔  
![Screenshot_20230311_104822_com rhmsoft edit](https://user-images.githubusercontent.com/56335408/224466387-2d00e219-f475-4a33-8509-c879c1f94dfc.jpg)

**Comment by xp12047** [comment]
我不知道该怎么让它生效。我放在rime文件夹下也在设定列表里面看到了。但它跟原来输入方式没啥区别

**Comment by Frefreak** [comment]
您好，我写的这个规则是辅助码为每个字的五笔编码(86)第一个字母
阿布 双拼是 aabu，五笔中`阿=bsk`，`布=dmh`，所以是`aabubd`，另外也保留了aabu本身这个编码
辅助码当时主要是想在重码时可以通过多打几个字母来唯一确定。

现在我再试了一下，现在生成字典的脚本在单字的编码处理时倒是把原来的2字母编码漏了，比如"发"，应该要有`fa`和`fant`两个，现在只有`fant`。如果您需要的话我可以把这部分补上。

> 跟原来输入方式没啥区别
这个具体期望的和实际的情况可以说明下不

另外是我最近开始学虎码了，所以这个repo后面应该也不怎么会更新了...

**Comment by xp12047** [comment]
> 您好，我写的这个规则是辅助码为每个字的五笔编码(86)第一个字母 阿布 双拼是 aabu，五笔中`阿=bsk`，`布=dmh`，所以是`aabubd`，另外也保留了aabu本身这个编码 辅助码当时主要是想在重码时可以通过多打几个字母来唯一确定。
> 
> 现在我再试了一下，现在生成字典的脚本在单字的编码处理时倒是把原来的2字母编码漏了，比如"发"，应该要有`fa`和`fant`两个，现在只有`fant`。如果您需要的话我可以把这部分补上。
> 
> > 跟原来输入方式没啥区别
> > 这个具体期望的和实际的情况可以说明下不
> 
> 另外是我最近开始学虎码了，所以这个repo后面应该也不怎么会更新了...

好，感谢!有空帮忙补一下吧。我下载仓库直接放到用户目录就行对吧？还执行那个py程序嘛？我执行了貌似也没反应。另外可以帮忙改两个脚本嘛？一个是修复现在的。一个能不能把每个提取每个汉字的前两笔五笔也就是两个字母。

**Comment by xp12047** [comment]
虎码比这个双拼？

**Comment by xp12047** [comment]
> 您好，我写的这个规则是辅助码为每个字的五笔编码(86)第一个字母 阿布 双拼是 aabu，五笔中`阿=bsk`，`布=dmh`，所以是`aabubd`，另外也保留了aabu本身这个编码 辅助码当时主要是想在重码时可以通过多打几个字母来唯一确定。
> 
> 现在我再试了一下，现在生成字典的脚本在单字的编码处理时倒是把原来的2字母编码漏了，比如"发"，应该要有`fa`和`fant`两个，现在只有`fant`。如果您需要的话我可以把这部分补上。
> 
> > 跟原来输入方式没啥区别
> > 这个具体期望的和实际的情况可以说明下不
> 
> 另外是我最近开始学虎码了，所以这个repo后面应该也不怎么会更新了...

我想请教下，如果三个字的辅码该怎么打？比如是阿布，难倒要打uiaabujbd嘛？

**Comment by Frefreak** [comment]
一开始我是想找个手机上更好用的输入法，所以开始看双拼（之前手机上一直是全拼）。后来观念转变了，感觉还是形码适合我，偶然看到虎码所以开始学的。

> 是阿布，难倒要打uiaabujbd嘛

是的，如果按照这个规则就是这样 uiaabu + **j** + **b**sk + **d**mh

**Comment by xp12047** [comment]
> 一开始我是想找个手机上更好用的输入法，所以开始看双拼（之前手机上一直是全拼）。后来观念转变了，感觉还是形码适合我，偶然看到虎码所以开始学的。
> 
> > 是阿布，难倒要打uiaabujbd嘛
> 
> 是的，如果按照这个规则就是这样 uiaabu + **j** + **b**sk + **d**mh

明白了，但这似乎和别的不太一样。这种句子不是一个辅码嘛？比如我，这三个字，算是一起的那么只取我的t五笔就好了。

**Comment by Frefreak** [comment]
> 好，感谢!有空帮忙补一下吧。我下载仓库直接放到用户目录就行对吧？还执行那个py程序嘛？我执行了貌似也没反应。另外可以帮忙改两个脚本嘛？

如果修改了脚本或改了data中的文件就需要重新执行，另外我提交前会把执行后的文件一起加入版本管理所以不用再执行（除非做了修改。

> 一个是修复现在的。一个能不能把每个提取每个汉字的前两笔五笔也就是两个字母。

提取前两笔这个可以给个例子不

**Comment by xp12047** [comment]
> > 好，感谢!有空帮忙补一下吧。我下载仓库直接放到用户目录就行对吧？还执行那个py程序嘛？我执行了貌似也没反应。另外可以帮忙改两个脚本嘛？
> 
> 如果修改了脚本或改了data中的文件就需要重新执行，另外我提交前会把执行后的文件一起加入版本管理所以不用再执行（除非做了修改。
> 
> > 一个是修复现在的。一个能不能把每个提取每个汉字的前两笔五笔也就是两个字母。
> 
> 提取前两笔这个可以给个例子不
> 
> > 比如我，这三个字，算是一起的那么只取我的t五笔就好了。
> 
> 不好意思，这句没太看明白，可以再解释下吗

比如"我字"要它的前两笔五笔字根'tr'。  
如果可以再给个条件，删除dist.txt文档里面汉字后面的字母，然后再加上补充每个汉字两个五笔字根，就更好了。我不会编程，哎，我自己搞了好久了差不多一天了还一头雾水。昨晚就看见你这个项目了我很兴奋。

**Comment by xp12047** [comment]
![IMG_20230311_163111](https://user-images.githubusercontent.com/56335408/224474044-c782cb62-a73d-4abf-b4a3-90fdb86345f6.jpg)
实际上午那个要求是给我用的"影子输入法"来用的。我觉得你的方法完全可以用在它上面。影子输入法不想小狼毫那么麻烦。但我看了我这个图觉得也不大行。因为那个厂的变体在五笔上面就一个字根嘛

**Comment by xp12047** [comment]
但是那个影子输入法兼容性很不好。不如小狼毫。所以，我想如果你有时间就帮我弄下小狼毫的那个配置。第二点请求不行就算了。

**Comment by Frefreak** [comment]
影子输入法这个截图的是导入辅助码用的吗，我之前给手心输入法试过貌似是可以的，就直接生成每个字的前两个编码就可以了

> 比如"我字"要它的前两笔五笔字根'tr'。

比如这个词“我的”，原来双拼编码`wode`，新字典要同时有`wode`和`wodetr` （多了'我'这个字的五笔编码前两个字母）这样吗
我可以再写个脚本按这种规则生成，这里的辅助码一定是第一个字的编码的前两个字母对吗？

> 如果可以再给个条件，删除dist.txt文档里面汉字后面的字母，然后再加上补充每个汉字两个五笔字根
这个是要生成类似
```
啊=kb
俺=wd
唉=kc
昂=jq
爱=ep
按=rp
澳=it
```
这样的文件吗？像截图那样增加辅助码？

**Comment by xp12047** [comment]
> 影子输入法这个截图的是导入辅助码用的吗，我之前给手心输入法试过貌似是可以的，就直接生成每个字的前两个编码就可以了
> 
> > 比如"我字"要它的前两笔五笔字根'tr'。
> 
> 比如这个词“我的”，原来双拼编码`wode`，新字典要同时有`wode`和`wodetr` （多了'我'这个字的五笔编码前两个字母）这样吗 我可以再写个脚本按这种规则生成，这里的辅助码一定是第一个字的编码的前两个字母对吗？
> 
> > 如果可以再给个条件，删除dist.txt文档里面汉字后面的字母，然后再加上补充每个汉字两个五笔字根
> > 这个是要生成类似
> 
> ```
> 啊=kb
> 俺=wd
> 唉=kc
> 昂=jq
> 爱=ep
> 按=rp
> 澳=it
> ```
> 
> 这样的文件吗？像截图那样增加辅助码？

对😊

**Comment by Frefreak** [comment]
我一会可以先生成txt那种格式的，这个很快，你先试试是否满足，如果还需要rime那种的我再按你说的实现下看看。

**Comment by xp12047** [comment]
> 我一会可以先生成txt那种格式的，这个很快，你先试试是否满足，如果还需要rime那种的我再按你说的实现下看看。

好，谢谢😊

**Comment by Frefreak** [comment]
@xp12047 
添加了：https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/anxiliary.txt
对应的生成脚本是https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/gen_anxiliary.py
用的还是rime-wubi86的dict文件，70781个字

**Comment by xp12047** [comment]
> @xp12047 添加了：https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/anxiliary.txt 对应的生成脚本是https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/gen_anxiliary.py 用的还是rime-wubi86的dict文件，70781个字

谢谢谢，我试试😊

**Comment by xp12047** [comment]
> @xp12047 添加了：https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/anxiliary.txt 对应的生成脚本是https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/gen_anxiliary.py 用的还是rime-wubi86的dict文件，70781个字

谢谢，好用是好用了。但是似乎有点问题。我怎么修改脚本让它只保留一个字母呢？我试了几次都失败了。在脚本目录终端运行。改成'是=j'就可以

**Comment by xp12047** [comment]
![图片](https://user-images.githubusercontent.com/56335408/224477072-cbda9a1c-8580-49e5-acc7-06ebd284aeba.png)
录了个视频太大了上传不了。  
![图片](https://user-images.githubusercontent.com/56335408/224477101-4a520dd5-cac2-4663-9f32-0dbb566d5461.png)
我想修改提取一个字母该怎么编辑脚本？谢谢

**Comment by Frefreak** [comment]
是要全部只保留一个字母吗，把这里的2改成1就可以了

https://github.com/Frefreak/rime-zrm-wubi/blob/870dcf7604624faba085662b0753721ca2fa3852/scripts/gen_anxiliary.py#L14


如果是特定一些字改的话就要加一些其他判断，如果字少的话可以直接这样：
```python

single_chars = set(['是', '的']) # 加上想要单个字母的字

with open('anxiliary.txt', 'w') as f:
    for ch, code in wubi_dict.items():
        if len(code) < 2:
            print(f"{ch} has code {code} whose length is smaller than 2")
        if ch in single_chars:
            f.write(f'{ch}={code[:1]}\n')
        else:
            f.write(f'{ch}={code[:2]}\n')
```

**Comment by xp12047** [comment]
> 是要全部只保留一个字母吗，把这里的2改成1就可以了
> 
> https://github.com/Frefreak/rime-zrm-wubi/blob/870dcf7604624faba085662b0753721ca2fa3852/scripts/gen_anxiliary.py#L14
> 
> 如果是特定一些字改的话就要加一些其他判断，如果字少的话可以直接这样：
> 
> ```python
> single_chars = set(['是', '的']) # 加上想要单个字母的字
> 
> with open('anxiliary.txt', 'w') as f:
>     for ch, code in wubi_dict.items():
>         if len(code) < 2:
>             print(f"{ch} has code {code} whose length is smaller than 2")
>         if ch in single_chars:
>             f.write(f'{ch}={code[:1]}\n')
>         else:
>             f.write(f'{ch}={code[:2]}\n')
> ```

对，全部改了。  但是。。
![图片](https://user-images.githubusercontent.com/56335408/224477416-e47bd662-ebb2-4d7f-a04e-d78ba8defde4.png)

**Comment by Frefreak** [comment]
可能跟环境的字符集有关。我加上了新的文件，可以直接用
https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/gen_anxiliary2.py
https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/anxiliary-simplified.txt

另外一个是原来我提取编码用的是全码，比如‘我’会取到它的全码，而不是一简`q`，新的这个脚本取的是简码（我感觉更可能是你想要的）

**Comment by xp12047** [comment]
> 可能跟环境的字符集有关。我加上了新的文件，可以直接用 https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/gen_anxiliary2.py https://github.com/Frefreak/rime-zrm-wubi/blob/master/scripts/anxiliary-simplified.txt
> 
> 另外一个是原来我提取编码用的是全码，比如‘我’会取到它的全码，而不是一简`q`，新的这个脚本取的是简码（我感觉更可能是你想要的）

谢谢，给你添麻烦了。

**Comment by Frefreak** [comment]
没事，有问题欢迎再提，可以直接reopen或加新issue

**Comment by xp12047** [comment]
> 没事，有问题欢迎再提，可以直接reopen或加新issue

好，谢谢！

**Comment by xp12047** [comment]
> > 没事，有问题欢迎再提，可以直接reopen或加新issue
> 
> 好，谢谢！

对不起在打扰你下。你有空的时候可以在更新下小狼毫rime上的版本吗？我需要它。最好改成像现在的简码不改简码也没关系只要能用就行。因为我现在用的这个影子输入法有bug。。我有点难受。。当然这个不着急我暂时用影子没关系。你有时间想起来了帮忙弄下就好。你之前弄得对我来说都很有用。因为有些公司里面安装rime不方便。不如影子。但影子那个总觉得哪里不对劲。

**Comment by Frefreak** [comment]
@xp12047 好，可以的

**Comment by xp12047** [comment]
> @xp12047 好，可以的

谢谢😊

**Comment by Frefreak** [comment]
@xp12047 您好，我新加了按如下规则生成的脚本和文件：
1. 每个汉字使用五笔的简码作为辅助码数据库
2. 每个字/词用第一个字的五笔编码作为辅助码（不足的就只用一个字母）

![image](https://user-images.githubusercontent.com/7122156/224603016-1d6c837b-c13d-4d2f-9293-712d9f3a694f.png)

**Comment by xp12047** [comment]
> @xp12047 您好，我新加了按如下规则生成的脚本和文件：
> 
> 1. 每个汉字使用五笔的简码作为辅助码数据库
> 2. 每个字/词用第一个字的五笔编码作为辅助码（不足的就只用一个字母）
> 
> ![image](https://user-images.githubusercontent.com/7122156/224603016-1d6c837b-c13d-4d2f-9293-712d9f3a694f.png)

厉害啊😁，太感谢了。辛苦了辛苦了!谢谢😊   
我想问下我该如何安装在rime上用？  
如果改成你原来的那种会不会也好用呢？改成全码  
我昨天又换成全码了，因为我发现我踏马快把五笔忘干净了。每个字取五笔全部的码，每个词也是，通常五笔大概四个码，但是也有三码的好像。反正全码就行。这样貌似能更快的找到所想要字但是同样也增加了按键次数。   
上面的请求可以不予理睬。最想知道的就是我该如何安装呢？覆盖原来的目录还是？

**Comment by Frefreak** [comment]
把zrm_wubi.dict.yaml.simplified覆盖原来的zrm_wubi.dict.yaml应该就可以了，只是dict文件变了。

> 如果改成你原来的那种会不会也好用呢？改成全码
我脑补原来那种（每个字的第一个五笔的字母连起来）会重码少一点，但是没有实际测试过

**Comment by xp12047** [comment]
> 把zrm_wubi.dict.yaml.simplified覆盖原来的zrm_wubi.dict.yaml应该就可以了，只是dict文件变了。
> 
> > 如果改成你原来的那种会不会也好用呢？改成全码
> 
> 我脑补原来那种（每个字的第一个五笔的字母连起来）会重码少一点，但是没有实际测试过

😄你真是好人。而且很优秀！算了就这么用吧。我就是想尽可能在用输入法的时候熟悉下它(五笔)。我下载文件直接覆盖可以嘛？

**Comment by xp12047** [comment]
> > 把zrm_wubi.dict.yaml.simplified覆盖原来的zrm_wubi.dict.yaml应该就可以了，只是dict文件变了。
> > > 如果改成你原来的那种会不会也好用呢？改成全码
> > 
> > 
> > 我脑补原来那种（每个字的第一个五笔的字母连起来）会重码少一点，但是没有实际测试过
> 
> 😄你真是好人。而且很优秀！算了就这么用吧。我就是想尽可能在用输入法的时候熟悉下它(五笔)。我下载文件直接覆盖可以嘛？

抱歉没好好看。我覆盖试试。谢谢谢

**Comment by Frefreak** [comment]
谢谢，举手之劳。把原来的配置备份后复制这个项目的yaml文件过去应该就可以了 （不太了解rime可不可以分目录保存配置文件，我对rime的配置很多也是一知半解 :joy:  

另外假如原来有文件的话感觉有时候会有干扰

**Comment by xp12047** [comment]
> 谢谢，举手之劳。把原来的配置备份后复制这个项目的yaml文件过去应该就可以了 （不太了解rime可不可以分目录保存配置文件，我对rime的配置很多也是一知半解 😂
> 
> 另外假如原来有文件的话感觉有时候会有干扰

好吧😊谢谢我试试。

**Comment by xp12047** [comment]
谢谢，我试了。但我没改成1码的居然也很好用啊啊！太感谢了。但是我想确定下你原来全码那个dict没什么问题吧就是你一开始自己弄得那种两码的，太感谢你了啊

**Comment by Frefreak** [comment]
那个我改了逻辑后重新生成了，简单测试了下是符合预期的

**Comment by xp12047** [comment]
> 那个我改了逻辑后重新生成了，简单测试了下是符合预期的

好，谢谢，

**Comment by xp12047** [comment]
真的很感谢。谢谢。我试用了。总体效果算是达到了想要的结果。但是这针对的貌似只能是单个文字和一些码数不多。我手机上也是拷贝了这套词典。 
我想说下情况。  
比如我打了一串字想要换掉其中一个的时候往往不行。字数少的候选有的倒是可以就是翻页没了  
![图片](https://user-images.githubusercontent.com/56335408/224622873-6ec6a68b-c049-41d2-9198-96db87182891.png)
像图上超过四个字或者三个字估计就不行了。即使翻页找。  
![图片](https://user-images.githubusercontent.com/56335408/224623085-1499801a-c4d4-41fd-971a-df10ed64733f.png)
  
![图片](https://user-images.githubusercontent.com/56335408/224623166-44d06187-25e1-4687-be92-4c4f57cb72ff.png)
我拉到最后发现。码数多了后它实际上还是自然码双拼。不是五笔。

**Comment by Frefreak** [comment]
因为它这个还是基于词库的，如果是词库没有的词组应该就是不行的。

比如
- "码字" -> mazi**ab** (ab假设是五笔编码)
- "效果" -> xcgo**cd** (cd假设是五笔编码)

那mazixcgo**abcd**这样不行是正常的，mazi**ab**xcgo**cd**应该是ok的吧

**Comment by xp12047** [comment]
> 因为它这个还是基于词库的，如果是词库没有的词组应该就是不行的。
> 
> 比如
> 
> * "码字" -> mazi**ab** (ab假设是五笔编码)
> * "效果" -> xcgo**cd** (cd假设是五笔编码)
> 
> 那mazixcgo**abcd**这样不行是正常的，mazi**ab**xcgo**cd**应该是ok的吧

对。词库如果没有就不行了。词库两个字以上的也不行。

**Comment by Frefreak** [comment]
> 词库两个字以上的也不行。

那这个好像不对，给个例子看看？

**Comment by xp12047** [comment]
> > 词库两个字以上的也不行。
> 
> 那这个好像不对，给个例子看看？

好  

https://user-images.githubusercontent.com/56335408/224627673-f01aa118-73c4-465a-9ccd-a9a89f02970f.mp4

电脑上录的也大手机上给你录看看

**Comment by xp12047** [comment]
https://user-images.githubusercontent.com/56335408/224630411-eb5a337c-7557-4c11-a2b0-7369900df8bb.mp4

**Comment by Frefreak** [comment]
“三个字”确实不在词库，所以不行也是正常的

![image](https://user-images.githubusercontent.com/7122156/224631511-5700ea68-13fd-490c-92d4-f5b2747805bb.png)
“我可”这个因为后面那种规则只使用第一个字的简码，就只有一个`q`了。不过可以看到现在少了`woke`这个 （改单字的编码逻辑影响到词了，我晚点更新下）

直接替换某个字的话，用词典这种方法感觉是不行的。

**Comment by xp12047** [comment]
> “三个字”确实不在词库，所以不行也是正常的
> 
> ![image](https://user-images.githubusercontent.com/7122156/224631511-5700ea68-13fd-490c-92d4-f5b2747805bb.png) “我可”这个因为后面那种规则只使用第一个字的简码，就只有一个`q`了。不过可以看到现在少了`woke`这个 （改单字的编码逻辑影响到词了，我晚点更新下）
> 
> 直接替换某个字的话，用词典这种方法感觉是不行的。

明白，谢谢。

**Comment by Frefreak** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/7122156/224643465-bbf84c7e-e0bd-4dcd-922c-9bba3572a386.png">
更新了

**Comment by xp12047** [comment]
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/7122156/224643465-bbf84c7e-e0bd-4dcd-922c-9bba3572a386.png">
> 
> 更新了

谢谢！

**Comment by xp12047** [comment]
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/7122156/224643465-bbf84c7e-e0bd-4dcd-922c-9bba3572a386.png">
> 
> 更新了

抱歉我还要打扰你下。月=ee，可词典里面似乎不对是et

**Comment by xp12047** [comment]
现在的情况有所改善。但它似乎不能精准定位了。以前。不知道是不是因为重码多了导致的。
月娥
![Screenshot_20230313_170239_com android chrome](https://user-images.githubusercontent.com/56335408/224654743-5d04101b-fa40-419c-84a2-a9de2f90d0ac.jpg)
![Screenshot_20230313_170227_com android chrome](https://user-images.githubusercontent.com/56335408/224654774-afcb3d28-22ad-4ead-b1e7-9374465fb3d7.jpg)

**Comment by xp12047** [comment]
我好像明白些了。想要用五笔作自然码辅码用每个汉字的前两笔不合适。因为有冲突重码。比如召字。它的自然码双拼也是vk，五笔也是。那么辅码它就没有了。  
![Screenshot_20230313_171819_com android chrome](https://user-images.githubusercontent.com/56335408/224658412-2ee2ce61-5bf8-436b-b0fd-304f82b13fdd.jpg)
这是输入两个vk的结果  
所以我觉得需要使用一码，也就是每个汉字的五笔的第一笔。vkv估计就可以

**Comment by Frefreak** [comment]
vkvk这个例子，往后翻页是不是有“找”这个字

我用的时候也是感觉词与字的重码有点高了，而且有一点是，只用双拼打出来的和带辅助码打出来的，频率数据库(userdb)是两个，也造成不是很好用

跟这个问题应该是类似的
https://github.com/mutoe/rime/issues/10

**Comment by Frefreak** [comment]
后面准备archive这个项目了，毕竟用不太到了

**Comment by xp12047** [comment]
> vkvk这个例子，往后翻页是不是有“召”这个字
> 
> 我用的时候也是感觉词与字的重码有点高了，而且有一点是，只用双拼打出来的和带辅助码打出来的，频率数据库(userdb)是两个，也造成不是很好用
> 
> 跟这个问题应该是类似的 [mutoe/rime#10](https://github.com/mutoe/rime/issues/10)

明白了，谢谢。对了你那个虎码学的怎么样了？

**Comment by Frefreak** [comment]
目前在练前500常用字了，还是很慢，而且经常和五笔的字根编码打架
再练段时间应该会好很多

**Comment by xp12047** [comment]
> 目前在练前500常用字了，还是很慢，而且经常和五笔的字根编码打架 再练段时间应该会好很多

为什么选择虎码啊，昨天看到个表形码，包括之前一直想练的郑码都挺好的

**Comment by Frefreak** [comment]
我被它声称的用算法选择出来的布局方案吸引了

另外你愿意的话欢迎发一封邮件给我进行后续讨论，issue里就不聊天了 :joy:

**Comment by xp12047** [comment]
> 我被它声称的用算法选择出来的布局方案吸引了
> 
> 另外你愿意的话欢迎发一封邮件给我进行后续讨论，issue里就不聊天了 😂

鞥😁
